[tox]
envlist = py311, py312, py313, py314, flake8
skip_missing_interpreters = true
isolated_build = true

[testenv]
extras = test
commands =
    pytest --basetemp={envtmpdir}

[testenv:flake8]
skip_install = true
deps = flake8
commands = flake8 firepit tests
